version: '2'
services:
  aleppo:
    # path to Aleppo
    build: ../aleppo
    ports:
      - "8089"
    volumes:
      - .:/dtb
    network_mode: host
  now-you-see-me:
    # path to Now You See Me
    build: ../now-you-see-me
    ports:
      - "6622"
    volumes:
      - .:/dtb
    network_mode: host
  splitter:
    image: registry.bukalapak.io/sre/gudang/pre-build/golang:0.1.0
    # path to splitter
    build: ../deploy/_output/splitter
    ports:
      - "6643"
    volumes:
      - .:/dtb
    network_mode: host
